/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './error.vue',
  ],
  theme: {
    extend: {
      colors: {
        // Using CSS variables for all colors
        'bg-primary': 'var(--color-bg-primary)',
        'bg-secondary': 'var(--color-bg-secondary)',
        'bg-tertiary': 'var(--color-bg-tertiary)',
        'border-primary': 'var(--color-border-primary)',
        'border-secondary': 'var(--color-border-secondary)',
        'border-light': 'var(--color-border-light)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-muted': 'var(--color-text-muted)',
        'text-inverse': 'var(--color-text-inverse)',
        'accent-primary': 'var(--color-accent-primary)',
        'accent-primary-dark': 'var(--color-accent-primary-dark)',
        'accent-primary-light': 'var(--color-accent-primary-light)',
        'accent-gold': 'var(--color-accent-gold)',
        'success': 'var(--color-success)',
        'success-dark': 'var(--color-success-dark)',
        'danger': 'var(--color-danger)',
        'danger-dark': 'var(--color-danger-dark)',
        'info': 'var(--color-info)',
        'info-dark': 'var(--color-info-dark)',
        'warning': 'var(--color-warning)',
        // Legacy names for backward compatibility
        parchment: 'var(--color-bg-primary)',
        'parchment-dark': 'var(--color-bg-secondary)',
        brown: 'var(--color-border-primary)',
        'brown-dark': 'var(--color-accent-primary-dark)',
        'brown-light': 'var(--color-accent-primary-light)',
        'brown-border': 'var(--color-border-secondary)',
        gold: 'var(--color-accent-gold)',
        'text-dark': 'var(--color-text-primary)',
        'text-brown': 'var(--color-text-secondary)',
        'green-hp': 'var(--color-success)',
        'green-hp-dark': 'var(--color-success-dark)',
        'red-damage': 'var(--color-danger)',
      },
      fontFamily: {
        cinzel: ['Cinzel', 'Georgia', 'Times New Roman', 'serif'],
        'cinzel-decorative': ['Cinzel Decorative', 'Georgia', 'Times New Roman', 'serif'],
        medieval: ['MedievalSharp', 'Georgia', 'Times New Roman', 'serif'],
        uncial: ['Uncial Antiqua', 'Georgia', 'Times New Roman', 'serif'],
      },
      boxShadow: {
        'dnd': 'var(--shadow-md)',
        'dnd-lg': 'var(--shadow-lg)',
        'dnd-inner': 'var(--shadow-inner)',
        'dnd-sm': 'var(--shadow-sm)',
      },
      spacing: {
        'xs': 'var(--spacing-xs)',
        'sm': 'var(--spacing-sm)',
        'md': 'var(--spacing-md)',
        'lg': 'var(--spacing-lg)',
        'xl': 'var(--spacing-xl)',
        '2xl': 'var(--spacing-2xl)',
      },
      borderRadius: {
        'dnd-sm': 'var(--radius-sm)',
        'dnd-md': 'var(--radius-md)',
        'dnd-lg': 'var(--radius-lg)',
      },
    },
  },
  plugins: [],
}
